def foo():
    raise Exception("blah")


def main():
    try:
        foo()
        try:
            foo()
        except Exception:
            pass
    except Exception:
        print("CAUGHT")
